// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.6
// source: analytics.proto

package analytics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AnalyticsService_FindAllFeedbacks_FullMethodName     = "/analytics.AnalyticsService/FindAllFeedbacks"
	AnalyticsService_ToggleFeedbackViewed_FullMethodName = "/analytics.AnalyticsService/ToggleFeedbackViewed"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsServiceClient interface {
	FindAllFeedbacks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FindAllFeedbacksResponse, error)
	ToggleFeedbackViewed(ctx context.Context, in *ToggleFeedbackViewedRequest, opts ...grpc.CallOption) (*ToggleFeedbackViewedResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) FindAllFeedbacks(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*FindAllFeedbacksResponse, error) {
	out := new(FindAllFeedbacksResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_FindAllFeedbacks_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) ToggleFeedbackViewed(ctx context.Context, in *ToggleFeedbackViewedRequest, opts ...grpc.CallOption) (*ToggleFeedbackViewedResponse, error) {
	out := new(ToggleFeedbackViewedResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_ToggleFeedbackViewed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility
type AnalyticsServiceServer interface {
	FindAllFeedbacks(context.Context, *emptypb.Empty) (*FindAllFeedbacksResponse, error)
	ToggleFeedbackViewed(context.Context, *ToggleFeedbackViewedRequest) (*ToggleFeedbackViewedResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticsServiceServer struct {
}

func (UnimplementedAnalyticsServiceServer) FindAllFeedbacks(context.Context, *emptypb.Empty) (*FindAllFeedbacksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllFeedbacks not implemented")
}
func (UnimplementedAnalyticsServiceServer) ToggleFeedbackViewed(context.Context, *ToggleFeedbackViewedRequest) (*ToggleFeedbackViewedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToggleFeedbackViewed not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_FindAllFeedbacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).FindAllFeedbacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_FindAllFeedbacks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).FindAllFeedbacks(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_ToggleFeedbackViewed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleFeedbackViewedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).ToggleFeedbackViewed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_ToggleFeedbackViewed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).ToggleFeedbackViewed(ctx, req.(*ToggleFeedbackViewedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAllFeedbacks",
			Handler:    _AnalyticsService_FindAllFeedbacks_Handler,
		},
		{
			MethodName: "ToggleFeedbackViewed",
			Handler:    _AnalyticsService_ToggleFeedbackViewed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics.proto",
}
